language: go
go:
  - 1.9.x
node_js:
  - "iojs"
  - "8"

cache: npm
install: true

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - sh build_dashboard.sh
  - docker build -t hehety/godfs-dashboard:latest .
  - docker push hehety/godfs-dashboard:latest
