language: go
go:
  - 1.8.x

install: true

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - sh build_dashboard.sh
  - docker build -t hehety/godfs-dashboard:latest
  - docker push hehety/godfs-dashboard:latest
